packages:
  - apps/*
  - packages/*

catalog:
  typescript: ^5.9.3
  "@types/node": ^22.18.10
  zod: ^3.25.76

catalogs:
  react19:
    react: ^19.2.0
    react-dom: ^19.2.0
    "@types/react": ^19.2.2
    "@types/react-dom": ^19.2.2


onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - nestjs-pino
  - sharp
