packages:
  - apps/*
  - packages/*

catalog:
  typescript: ^5.9.3
  "@types/node": ^22.18.10
  zod: ^3.25.76

catalogs:
  react19:
    react: ^19.2.0
    react-dom: ^19.2.0
    "@types/react": ^19.2.2
    "@types/react-dom": ^19.2.2
  vite:
    vite: ^7.1.10
    vite-tsconfig-paths: ^5.1.4
    "@vitejs/plugin-react": ^4.7.0
    vitest: ^3.2.4


onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - nestjs-pino
  - sharp
