name: 'Restore Workspace'
description: 'Restores the workspace from cache'

runs:
  using: 'composite'
  steps:
    - name: Restore workspace
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}
        key: repo-${{ github.sha }}
