services:
  redis-commander:
    container_name: flemme_redis_commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:${REDIS_PORT}:0:${REDIS_PASSWORD:-redis_password}
    ports:
      - '8081:8081'
    depends_on:
      - redis
