name: CI

on:
  pull_request:
    branches:
      - development
      - main
    branches-ignore:
      - renovate/** 

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: ✨ Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-workspace
      - name: Run lint
        run: pnpm run test:lint
  
  format:
    name: 📝 Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-workspace
      - name: Run format
        run: pnpm run test:format

  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-workspace
      - name: Run tests
        run: pnpm run test

