name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  release:
    name: 🚀 Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-workspace
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62
        with:
          files: |
            packages/*/package.json
            apps/*/package.json

      - name: Create GitHub Releases
        if: steps.changed-files.outputs.all_changed_files != ''
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            pkg=$(dirname "$file")
            NAME=$(basename "$pkg")
            VERSION=$(jq -r .version "$pkg/package.json")

            echo "📦 Creating release for $NAME v$VERSION"

            if [ -f "$pkg/CHANGELOG.md" ]; then
              BODY=$(awk '/^## /{if (p) exit; p=1} p' "$pkg/CHANGELOG.md")
            else
              BODY="No changelog available."
            fi

            gh release create "$NAME-v$VERSION" \
              --title "$NAME v$VERSION" \
              --notes "$BODY" \
              --target main || echo "❌ Error creating release $NAME-v$VERSION"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}