name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  setup:
    name: 🔧 Setup & Cache
    runs-on: ubuntu-latest
    steps:
      - name: Setup Workspace
        uses: ./.github/setup-workspace
  
  build:
    name: 🏗️ Build
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Restore Workspace
        uses: ./.github/restore-workspace
      - name: Run build
        run: pnpm turbo run build

  versionning:
    name: ✨ Versionning
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Restore Workspace
        uses: ./.github/restore-workspace
      - name: Run versionning
        run: echo "Versionning"

  tags:
    name: 🎨 Tags
    runs-on: ubuntu-latest
    needs: versionning
    steps:
      - name: Restore Workspace
        uses: ./.github/restore-workspace
      - name: Run tags
        run: echo "Tags"